version: '2'
services:
  nginx:
    image: kayachanoi/nginx:dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www:/www
    mem_limit: 134217728
    cpu_shares: 100
    links:
      - php
  php:
    image: kayachanoi/php
    volumes:
      - /www:/www
    mem_limit: 134217728
    cpu_shares: 100
    links:
      - mysql
      - redis
  redis:
    image: kayachanoi/redis
    ports: 
      - "6389:6389"
    mem_limit: 134217728
  mysql: 
    image: kayachanoi/mariadb
    mem_limit: 134217728
    cpu_shares: 100
  # mysql: 
  #   image: mysql
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: root123
  #   mem_limit: 134217728
  #   cpu_shares: 100
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      PMA_HOST: mysql
    mem_limit: 134217728
    cpu_shares: 100
    links:
      - mysql