version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - E:/docker/share/www:/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/site-enable:/etc/nginx/site-enable      
    links:
      - php
  # php:
  #   build: ./php-fpm    
  #   volumes:
  #     - E:/docker/share/www:/www
  #     - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini
  php:
    build: ./php
    volumes:
      - E:/docker/share/www:/www
  mysql:
    build: 
      context: ./mysql
      args:
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: root123
    # volumes:
      # - E:/docker/share/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    build: ./redis
    ports: 
      - "6389:6389"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      PMA_HOST: mariadb
  mariadb:
    build: 
      context: ./mariadb
      args:
        MYSQL_DATABASE: db_homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: root1234        
    ports:
      - "3306:3306"